### ISSUE TITLE
Boton fuera de lugar 

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel#35]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que el boton "Registrarse" y "Entrar" se encuentren correctamente.

## Resultado actual

• Los botones no se visualizan en su totalidad.

## Captura

![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/9b0ec6af-b944-46c8-92d5-b91ab1bd933e)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/81e46e8f-89fb-46b8-acd0-bd8fdc3e3c2e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by victoriacavanna** [comment]
Issue Resuelto. 
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/126695867/a8826f8e-6698-4c5d-9fa0-b2ed575c536a)
