### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel#36]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un nuevo usuario.

## Resultado esperado

• Que al finalizar el registro encontrar un aviso que me informe que me registre exitosamente. 
• Que no se permitan colocar numero ni signos en el nombre del usuario.

## Resultado actual

• Al finalizar el registro me avisa que el correo que proporcione ya esta en uso pero nunca me avise que ya estoy registrado.
• Se permiten colocar numeros y signos en el nombre del usuario.

## Captura

![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/76914e6c-f56d-422d-8a44-cd7d696d55fb)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/1e7b0cae-4fa0-4303-8153-4d430c0fbde8)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/4bd6d04e-2e80-4ba9-87c6-ffaab2e4b43a)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by victoriacavanna** [comment]
Issue Resuelto. 
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/126695867/9f87ec44-856e-4cac-9057-c8c8d15657ef)
