### ISSUE TITLE
Eliminar console.log

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel#37]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• No encontrar ningún console.log que muestre informacion por la consola

## Resultado actual

• Se encuentra información de console.log en la consola.

## Captura

![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/bea616e7-80ad-47e0-ac27-e66ae7c63bb0)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/0a19cf74-c50c-401d-b430-cc1cd5c897b6)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by victoriacavanna** [comment]
Issue resuelto. 
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/126695867/9d73b43b-f646-47d7-9021-e555cca9b663)
