### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel#38]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Poder enviar mi consulta sin ningún problema.

## Resultado actual

• A la hora de enviar mi consulta se genera un error y se muestra información por la consola (Eliminar los console.log).

## Captura

![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/a1e8f086-5ac9-4e92-bb2d-52fa6440aa57)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by victoriacavanna** [comment]
Issue resuelto.

![issueContacto](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/126695867/6d0a2903-b55f-42ef-93f4-66899e9ce5d9)
