### ISSUE TITLE
Seccion habitaciones

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel#39]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Al ingresar a la sección de "habitaciones" encontrar dicho contenido.

## Resultado actual

• Al ingresar no se encuentra ningún tipo de contenido o información de las habitaciones.

## Posible solucion.

• Al hacer click en la sección "Habitaciones" del nav que esta redirija a una 404 como los demás botones que tienen esta mención.

Ejemplo: Si quiero entrar a la seccion de habitaciones desde el footer me redirige a una page 404, podrían repetir esto pero en el boton del nav.

## Captura

• Boton de Nav
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/6c5dea7d-1e76-4b66-82cf-047cf8e9569e)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/1c7b0fa0-3fb4-473d-a33a-42f84b68145c)

• Boton de Footer 
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/4aa43bd9-4bd1-463d-8f4a-d804f9077faf)
![image](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/53904695/28fca2ac-2761-4464-b37b-6ed2bebdec1f)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by victoriacavanna** [comment]
![issueHabitaciones](https://github.com/samuelsantillan/Code-Scape-Hotel/assets/126695867/1081f6d4-0ff8-44bb-8f00-d6d7bced1c46)
Issue resuelto.
